# Generated by Django 2.0.2 on 2018-03-28 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('winereviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'varieties'},
        ),
        migrations.AlterModelOptions(
            name='winery',
            options={'verbose_name_plural': 'wineries'},
        ),
        migrations.AddField(
            model_name='variety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
