# Generated by Django 2.0.2 on 2018-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winereviews', '0002_auto_20180328_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='varietal',
            field=models.CharField(default='var', max_length=255),
            preserve_default=False,
        ),
    ]
